name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  container-texlive:
    runs-on: ubuntu-latest
    container: ghcr.io/dante-ev/texlive:edge
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Release
      run: chmod +x ./release.sh && ./release.sh

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
          artifacts: "result.pdf"
          bodyFile: "README.md"
          token: ${{ secrets.TOKEN }}



