name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Docker build
      run: docker build -t temp .

    - name: Docker run
      run: docker run temp

    - name: Archive generated PDF file
      uses: actions/upload-artifact@v4
      with:
        name: /demo.pdf
        path: /demo.pdf



